project:
  type: website
  resources: figures

website:
  repo-url: https://github.com/OnroerendErfgoed/brdr
  repo-actions: [ source, issue ]
  title: "BRDR - Aligning borders"
  navbar:
    logo: "static/logo.svg"
    left:
      - text: Home
        href: index.qmd
        icon: house-fill
      - text: Reference
        href: reference/index.qmd
      - text: Examples
        href: examples.qmd
      - text: Q & A
        href: qa.qmd

lang: en

metadata-files:
  - reference/_sidebar.yml

highlight-style: github-dark
format:
  html:
    theme:
      - static/custom.scss
    code-fold: false
    embed-resources: false
    toc: true
    toc-location: "right"

quartodoc:
  dir: reference  # Make sure it is explicit
  render_interlinks: true
  package: brdr

  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  sections:
    - title: Aligner
      package: brdr.aligner
      desc: Aligner class of the brdr package.
      contents:
        - Aligner
        - AlignerResult
    - title: AlignerFeatures
      package: brdr.feature_data
      desc: Classes for the thematic and reference data to be used by the Aligner
      contents:
        - AlignerFeatureCollection
        - AlignerFeature
    - title: Loaders
      package: brdr.loader
      desc: Loaders to load data
      contents:
        - Loader
        - DictLoader
        - GeoJsonLoader
        - GeoJsonFileLoader
        - GeoJsonUrlLoader
        - OGCFeatureAPIReferenceLoader
        - WFSReferenceLoader
    - title: Processors
      package: brdr.processor
      desc: Processor algorithms
      contents:
        - BaseProcessor
        - AlignerGeometryProcessor
        - DieussaertGeometryProcessor
        - NetworkGeometryProcessor
        - SnapGeometryProcessor
        - TopologyProcessor
    - title: Enumerators
      package: brdr.enums
      desc: Enums used in the brdr package.
      contents:
        - FullReferenceStrategy
        - AlignerResultType
        - OpenDomainStrategy
        - DiffMetric
        - ProcessRemark
        - Evaluation
        - SnapStrategy
        - PredictionStrategy
        - ProcessorID
    - title: Typings
      package: brdr.typings
      desc: Typings used in 'brdr'
      contents:
        - ProcessResult
    - title: Configs
      package: brdr.configs
      desc: Configs used in 'brdr' Aligner & Processor
      contents:
        - ProcessorConfig
        - AlignerConfig
    - title: GRB (Flanders-specific)
      package: brdr.be.grb
      desc: GRB (Flanders-specific) classes,methods, enumerators,...
      contents:
        - name: loader.GRBActualLoader
        - name: loader.GRBFiscalParcelLoader
        - name: loader.GRBSpecificDateParcelLoader
        - name: grb.update_featurecollection_to_actual_grb
        - name: utils.is_grb_changed
        - name: utils.get_affected_ids_by_grb_change
        - name: enums.GRBType
    - title: OSM
      package: brdr.osm
      desc: OpenStreetMap (OSM) classes,methods, enumerators,...
      contents:
        - name: loader.OSMLoader
    - title: Visualization-functions (optional by pip install brdr[viz])
      package: brdr.viz
      desc: OpenStreetMap (OSM) classes,methods, enumerators,...
      contents:
        - name: show_map
        - name: plot_difference_by_relevant_distance
        - name: animated_map
        - name: print_observation_of_aligner_results


          
