project:
  type: website
  resources: figures

website:
  title: "BRDR - Aligning borders"
  navbar:
    logo: "static/logo.svg"
    left:
      - text: Home
        href: index.qmd
        icon: house-fill
      - text: Reference
        href: reference/index.qmd
#      - text: Examples
#        href: examples.qmd

lang: en

metadata-files:
  - reference/_sidebar.yml

highlight-style: github-dark
format:
  html:
    theme:
      - static/custom.scss
    code-fold: false
    embed-resources: false
    toc: true
    toc-location: "right"

quartodoc:
  dir: reference  # Zorg dat dit expliciet is
  render_interlinks: true
  package: brdr

  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  sections:
    - title: Aligner
      package: brdr.aligner
      desc: Aligner class of the brdr package.
      contents:
        - Aligner
        - AlignerResult
    - title: AlignerFeatures
      package: brdr.feature_data
      desc: Classes for the thematic and reference data to be used by the Aligner
      contents:
        - AlignerFeatureCollection
        - AlignerFeature
    - title: Loaders
      package: brdr.loader
      desc: Loaders to load data
      contents:
        - Loader
        - DictLoader
        - GeoJsonLoader
        - GeoJsonFileLoader
        - GeoJsonUrlLoader
        - OGCFeatureAPIReferenceLoader
        - WFSReferenceLoader
    - title: Processors
      package: brdr.processor
      desc: Processor algorithms
      contents:
        - BaseProcessor
        - AlignerGeometryProcessor
        - DieussaertGeometryProcessor
        - NetworkGeometryProcessor
        - SnapGeometryProcessor
        - TopologyProcessor
    - title: Enumerators
      package: brdr.enums
      desc: Enums used in the brdr package.
      contents:
        - FullReferenceStrategy
        - AlignerResultType
        - OpenDomainStrategy
        - DiffMetric
        - ProcessRemark
        - Evaluation
        - SnapStrategy
        - PredictionStrategy
        - ProcessorID
    - title: Typings
      package: brdr.typings
      desc: Typings used in 'brdr'
      contents:
        - ProcessResult
    - title: GRB (Flanders-specific)
      package: brdr.be.grb
      desc: GRB (Flanders-specific) classes,methods, enumerators,...
      contents:
        - name: loader.GRBActualLoader
        - name: loader.GRBFiscalParcelLoader
        - name: loader.GRBSpecificDateParcelLoader
        - name: grb.update_featurecollection_to_actual_grb
        - name: enums.GRBType
#    - title: OSM
#      package: brdr.osm
#      desc: OpenStreetMap (OSM) classes,methods, enumerators,...
#      contents:
#        - name: loader.OSMLoader


          
